### ISSUE TITLE
Migration causes initContainer crash loop

### ISSUE THREAD

**Issue by slemrmartin** [RedHatInsights/sources-api#304]
Caused by #303

```
oc logs sources-api-1071-5q57j -c sources-api-seed
Unable to lookup hostname No such file or directory - hostname
GraphQL::ScalarType.define will be removed in GraphQL-Ruby 2.0; use a class-based definition instead. See https://graphql-ruby.org/schema/class_based_api.html.
  -> called from /usr/share/gems/gems/insights-api-common-5.0.0/lib/insights/api/common/graphql/types/date_time.rb:6:in `<module:Types>'
GraphQL::ScalarType.define will be removed in GraphQL-Ruby 2.0; use a class-based definition instead. See https://graphql-ruby.org/schema/class_based_api.html.
  -> called from /usr/share/gems/gems/insights-api-common-5.0.0/lib/insights/api/common/graphql/types/query_filter.rb:6:in `<module:Types>'
GraphQL::ScalarType.define will be removed in GraphQL-Ruby 2.0; use a class-based definition instead. See https://graphql-ruby.org/schema/class_based_api.html.
  -> called from /usr/share/gems/gems/insights-api-common-5.0.0/lib/insights/api/common/graphql/types/query_sort_by.rb:6:in `<module:Types>'
{"@timestamp":"2021-01-22T12:54:39.176886 ","hostname":"sources-api-1071-5q57j","pid":1,"tid":"2b0daa31c9cc","level":"info","message":"Sources API availability_status listener started..."}
{"@timestamp":"2021-01-22T12:54:41.783576 ","hostname":"sources-api-1071-5q57j","pid":1,"tid":"2b0da869b974","level":"debug","message":"   (0.4ms)  SELECT pg_try_advisory_lock(5025936724907480445)"}
{"@timestamp":"2021-01-22T12:54:41.878436 ","hostname":"sources-api-1071-5q57j","pid":1,"tid":"2b0da869b974","level":"debug","message":"   (0.7ms)  SELECT \"schema_migrations\".\"version\" FROM \"schema_migrations\" ORDER BY \"schema_migrations\".\"version\" ASC"}
{"@timestamp":"2021-01-22T12:54:41.879654 ","hostname":"sources-api-1071-5q57j","pid":1,"tid":"2b0da869b974","level":"info","message":"Migrating to MoveArnAuthToUsername (20210121161913)"}
{"@timestamp":"2021-01-22T12:54:41.881777 ","hostname":"sources-api-1071-5q57j","pid":1,"tid":"2b0da869b974","level":"debug","message":"   (0.4ms)  BEGIN"}
== 20210121161913 MoveArnAuthToUsername: migrating ============================
{"@timestamp":"2021-01-22T12:54:42.074656 ","hostname":"sources-api-1071-5q57j","pid":1,"tid":"2b0da869b974","level":"debug","message":"  Authentication Load (1.6ms)  SELECT \"authentications\".* FROM \"authentications\" WHERE \"authentications\".\"authtype\" IN ($1, $2)  [[\"authtype\", \"arn\"], [\"authtype\", \"cloud-meter-arn\"]]"}
{"@timestamp":"2021-01-22T12:54:42.281086 ","hostname":"sources-api-1071-5q57j","pid":1,"tid":"2b0da869b974","level":"debug","message":"  Application Load (0.7ms)  SELECT  \"applications\".* FROM \"applications\" WHERE \"applications\".\"id\" = $1 LIMIT $2  [[\"id\", 16702], [\"LIMIT\", 1]]"}
{"@timestamp":"2021-01-22T12:54:42.282254 ","hostname":"sources-api-1071-5q57j","pid":1,"tid":"2b0da869b974","level":"debug","message":"  Application Load (0.4ms)  SELECT  \"applications\".* FROM \"applications\" WHERE \"applications\".\"id\" = $1 LIMIT $2  [[\"id\", 16413], [\"LIMIT\", 1]]"}
{"@timestamp":"2021-01-22T12:54:42.283270 ","hostname":"sources-api-1071-5q57j","pid":1,"tid":"2b0da869b974","level":"debug","message":"  Application Load (0.4ms)  SELECT  \"applications\".* FROM \"applications\" WHERE \"applications\".\"id\" = $1 LIMIT $2  [[\"id\", 16996], [\"LIMIT\", 1]]"}
{"@timestamp":"2021-01-22T12:54:42.377788 ","hostname":"sources-api-1071-5q57j","pid":1,"tid":"2b0da869b974","level":"debug","message":"  Endpoint Load (0.7ms)  SELECT  \"endpoints\".* FROM \"endpoints\" WHERE \"endpoints\".\"id\" = $1 LIMIT $2  [[\"id\", 16297], [\"LIMIT\", 1]]"}
  /opt/sources-api/v2_key doesn't exist!
  On an appliance, it should be generated on boot by evmserverd.

  If you're a developer, you can copy the /opt/sources-api/v2_key.dev to /opt/sources-api/v2_key.

  Caution, using the developer key will allow anyone with the public developer key to decrypt the two-way
  passwords in your database.
{"@timestamp":"2021-01-22T12:54:42.473489 ","hostname":"sources-api-1071-5q57j","pid":1,"tid":"2b0da869b974","level":"debug","message":"   (0.8ms)  ROLLBACK"}
{"@timestamp":"2021-01-22T12:54:42.474364 ","hostname":"sources-api-1071-5q57j","pid":1,"tid":"2b0da869b974","level":"debug","message":"   (0.6ms)  SELECT pg_advisory_unlock(5025936724907480445)"}
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

can not decrypt v2_key encrypted string
/usr/share/gems/gems/manageiq-password-0.3.0/lib/manageiq/password.rb:43:in `rescue in decrypt'
/usr/share/gems/gems/manageiq-password-0.3.0/lib/manageiq/password.rb:40:in `decrypt'
/usr/share/gems/gems/manageiq-password-0.3.0/lib/manageiq/password.rb:72:in `decrypt'
/opt/sources-api/app/models/concerns/password_concern.rb:26:in `block in encrypt_column'
/opt/sources-api/db/migrate/20210121161913_move_arn_auth_to_username.rb:8:in `block (2 levels) in up'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/relation/delegation.rb:71:in `each'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/relation/delegation.rb:71:in `each'
/opt/sources-api/db/migrate/20210121161913_move_arn_auth_to_username.rb:4:in `block in up'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:265:in `transaction'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:212:in `transaction'
/opt/sources-api/db/migrate/20210121161913_move_arn_auth_to_username.rb:3:in `up'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:817:in `exec_migration'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:797:in `block in migrate'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:796:in `migrate'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:977:in `migrate'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1343:in `block in ddl_transaction'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:212:in `transaction'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1343:in `ddl_transaction'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1262:in `each'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1210:in `block in migrate'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1210:in `migrate'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1036:in `up'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1011:in `migrate'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <top (required)>'
/usr/share/gems/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'

Caused by:
ManageIQ::Password::PasswordError: can not decrypt v2_key encrypted string
/usr/share/gems/gems/manageiq-password-0.3.0/lib/manageiq/password.rb:43:in `rescue in decrypt'
/usr/share/gems/gems/manageiq-password-0.3.0/lib/manageiq/password.rb:40:in `decrypt'
/usr/share/gems/gems/manageiq-password-0.3.0/lib/manageiq/password.rb:72:in `decrypt'
/opt/sources-api/app/models/concerns/password_concern.rb:26:in `block in encrypt_column'
/opt/sources-api/db/migrate/20210121161913_move_arn_auth_to_username.rb:8:in `block (2 levels) in up'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/relation/delegation.rb:71:in `each'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/relation/delegation.rb:71:in `each'
/opt/sources-api/db/migrate/20210121161913_move_arn_auth_to_username.rb:4:in `block in up'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:265:in `transaction'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:212:in `transaction'
/opt/sources-api/db/migrate/20210121161913_move_arn_auth_to_username.rb:3:in `up'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:817:in `exec_migration'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:797:in `block in migrate'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:796:in `migrate'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:977:in `migrate'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1343:in `block in ddl_transaction'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:212:in `transaction'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1343:in `ddl_transaction'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1262:in `each'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1210:in `block in migrate'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1210:in `migrate'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1036:in `up'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1011:in `migrate'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <top (required)>'
/usr/share/gems/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'

Caused by:
NoMethodError: undefined method `decrypt64' for nil:NilClass
/usr/share/gems/gems/manageiq-password-0.3.0/lib/manageiq/password.rb:41:in `decrypt'
/usr/share/gems/gems/manageiq-password-0.3.0/lib/manageiq/password.rb:72:in `decrypt'
/opt/sources-api/app/models/concerns/password_concern.rb:26:in `block in encrypt_column'
/opt/sources-api/db/migrate/20210121161913_move_arn_auth_to_username.rb:8:in `block (2 levels) in up'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/relation/delegation.rb:71:in `each'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/relation/delegation.rb:71:in `each'
/opt/sources-api/db/migrate/20210121161913_move_arn_auth_to_username.rb:4:in `block in up'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:265:in `transaction'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:212:in `transaction'
/opt/sources-api/db/migrate/20210121161913_move_arn_auth_to_username.rb:3:in `up'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:817:in `exec_migration'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:797:in `block in migrate'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:416:in `with_connection'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:796:in `migrate'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:977:in `migrate'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1343:in `block in ddl_transaction'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/transactions.rb:212:in `transaction'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1343:in `ddl_transaction'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1262:in `each'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1210:in `block in migrate'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1210:in `migrate'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1036:in `up'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/migration.rb:1011:in `migrate'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/usr/share/gems/gems/activerecord-5.2.4.4/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <top (required)>'
/usr/share/gems/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

```

**Comment by slemrmartin** [comment]
@lindgrenj6 please :eyes:

**Comment by lindgrenj6** [comment]
https://github.com/RedHatInsights/e2e-deploy/pull/2676

**Comment by lindgrenj6** [comment]
that wasn't enough!
https://github.com/RedHatInsights/e2e-deploy/pull/2677
+
https://github.com/RedHatInsights/sources-api/pull/305

The deployment worked after this.
